server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:monolith_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgrespassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Okta / Google OpenID Connect (OIDC) Single Sign-On Configuration
okta.domain=${OKTA_DOMAIN:integrator-7068519.okta.com}
okta.api.token=${OKTA_API_TOKEN:00qyLPRc1YZepKM-rPPnPt08-fB1hGNXrF95WK0-Ed}

spring.security.oauth2.client.registration.okta.client-id=${OKTA_CLIENT_ID:0oa16mylvse2bXlNT698}
spring.security.oauth2.client.registration.okta.client-secret=${OKTA_CLIENT_SECRET:GN3IFDqQ_YtrLyFkJk9zNCcpsu5FcpaNvALOifeYPwTUHjtpza3wKyVaNkJwFgGA}
spring.security.oauth2.client.registration.okta.scope=openid,profile,email
spring.security.oauth2.client.provider.okta.issuer-uri=${OKTA_ISSUER_URI:https://${okta.domain}/oauth2/default}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:922391162058-657mnd5ve8lgavvt3kgd7ifg1hppj88n.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
